// <auto-generated />
namespace Project_MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBirthDateToCustomer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBirthDateToCustomer1));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141241278_addBirthDateToCustomer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
